# Model configurations

COLLECTION_NAME : "test-deepseek-r1"

available_models:
  - "deepseek-r1:1.5b"
  - "gemma3:1b"
  - "llama3.2"
  - "qwen2.5:1.5b"
  - "deepseek-r1:7b"

model: "deepseek-r1:1.5b"

temperature: 0.3