defaults:
  - model: default
  - training: default
  - processing: default
  - web_search : default
  - _self_

# Application-wide settings
app:
  collection_name: "test-deepseek-r1"
  rag_enabled: true
  similarity_threshold: 0.7
  default_model: "deepseek-r1:1.5b"


