name: RAG Test Runner
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train rag
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANGTRACE_API_KEY: ${{ secrets.LANGTRACE_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
          python rag_test.py
          echo "## Test Results" 
          cml comment create cml_report.txt
