name: RAG Test Runner

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # Removed container to avoid GLIBC conflicts
    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cml==0.19.0  # Pinned stable version

      - name: Run RAG tests
        env:
          LANGTRACE_API_KEY: ${{ secrets.LANGTRACE_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python rag_test.py > test_results.txt 2>&1 || true
          echo "## 🧪 Test Results" > report.md
          cat test_results.txt >> report.md

      - name: Publish CML Report
        uses: iterative/setup-cml@v2  # More reliable than direct command
        with:
          version: '0.19.0'  # Pinned version
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-send-comment report.md  # Preferred over 'comment create'
